### ISSUE TITLE
Support react.lazy

### ISSUE THREAD

**Issue by shapeshifta78** [natahouse/react-snap#37]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Please add support for react-lazy. The only viable option at the moment (at least partly working for me) is to use loadable components which is totally outdated as 2.2.3. I get mixed prerendered results here, so sometimes it works and sometimes it does not.

**Describe the solution you'd like**
Support of react.lazy

**Describe alternatives you've considered**
Loadable components 2.2.3 only partly working

**Teachability, Documentation, Adoption, Migration Strategy**
Usage of async component rendering

**Comment by philipeatela** [comment]
This would be a useful feature, but we are not actively implementing new things on this project anymore, so I believe it's unlikely that it will be implemented any time soon, since it can be a little bit complicated. We might implement some things but mostly smaller and easier to implement changes.

Feel free to come up with a PR if you wish though, and I might be able to help with reviewing/theorycrafting how to implement it.
